### ISSUE TITLE
ECR TF Serving Containers also return entire image string 

### ISSUE THREAD

**Issue by martham93** [developmentseed/ml-enabler-deprecated#19]
for ECR tf-serving image created in addition to the S3 path can we also return in the UI a string like `552819999234.dkr.ecr.us-east-1.amazonaws.com/ml-enabler-staging-ecr:models-4-prediction-27` for prediction use from ECR instead of docker-hub for use with chip-n-scale. 

<img width="948" alt="Screen Shot 2020-03-31 at 9 07 51 AM" src="https://user-images.githubusercontent.com/13889100/78051477-fab9cf00-733a-11ea-88a6-3e464605ae9f.png">

cc @ingalls

**Comment by ingalls** [comment]
@martham93 We have mostly removed the need to run chip-n-scale stacks at this point. Is this OK to close with no action? Or is it still something you need.
