### ISSUE TITLE
NPZ Export

### ISSUE THREAD

**Issue by ingalls** [developmentseed/ml-enabler-deprecated#34]
### Context

In order to retrain models, we need to be able to export the validated predictions in the NPZ format. The following is a rough guide for this work

### Actions

- We can modify the existing [export API](https://github.com/developmentseed/ml-enabler/blob/master/ml_enabler/__init__.py#L69) to support the NPZ format
- The code for this export class exists [here](https://github.com/developmentseed/ml-enabler/blob/master/ml_enabler/api/ml.py#L386)
- Add support for the `npz` with the correct mime time [here](https://github.com/developmentseed/ml-enabler/blob/master/ml_enabler/api/ml.py#L453-L458) While you are in there, lets also add an else statement that errors if the req_format is not known. An exmaple of returning an error to the user can be found [here](https://github.com/developmentseed/ml-enabler/blob/master/ml_enabler/api/ml.py#L572-L575). 5xx errors are for server errors, 4xx errors are for user errors.
- In the [generate function](https://github.com/developmentseed/ml-enabler/blob/master/ml_enabler/api/ml.py#L413-L44) add your conversion to NPZ

cc/ @geohacker @martham93

**Comment by martham93** [comment]
thanks for this write up! I'm excited to start contributing to the ml-enabler code base. 

Ultimately for re-training we'll need tf-records which can be easily generated from a `data.npz` file that has the numpy representation of an image tile, and the label. The flow for that is database => data.npz => TFrecords

As first steps, to start I'll work on having: 

- [x]  an export function to the get `labels.npz` file will have the x-y-z tile id as the key, and the labels as values. The labels will come from the rounded version of the prediction. For binary models they will be `([1, 0])` or `([0, 1])` 

- [x] add validated property to all export options (geojson, csv ect) - to indicate if user has validated a prediction or not 

- [x] have geojson export download with `.geojson` extension and not `._geosjon`

**Comment by ingalls** [comment]
@martham93 shipped NPZ Export - https://github.com/developmentseed/ml-enabler/pull/35
