### ISSUE TITLE
Change Map Colors 

### ISSUE THREAD

**Issue by martham93** [developmentseed/ml-enabler-deprecated#64]
### Context

currently inferences are displayed in red, validated predictions are in green, and invalid predictions are in white. 
This needs be changed to an accessible color scheme. 

Still need to confirm that is is an accessible color scheme, but the[ la croix themed colors are fun](https://github.com/johannesbjork/LaCroixColoR), and we could take the hex codes from these palettes. 

### Actions
- [x] Add new colour scheme for map
- [x] Add legend to explain colours

cc @ingalls

**Comment by ingalls** [comment]
When we do this let's also add a legend to the map

**Comment by martham93** [comment]
addressed in #83
